name: GitHubActions Release

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    


    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t abhishek6774/actions_repo
      - run: echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - run: docker push abhishek6774/actions_repo
  
